apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: odf-hub
  namespace: openshift-gitops
spec:
  generators:
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          usage: management
      requeueAfterSeconds: 30
  template:
    metadata:
      labels:
        velero.io/exclude-from-backup: "true"
      name: odf-{{name}}
    spec:
      destination:
        namespace: openshift-storage
        server: '{{server}}'
      project: default
      source:
        helm:
          parameters:
          - name: odf.channel
            value: stable-4.12
          - name: odf.startingCSV
            value: odf-operator.v4.12.0
          - name: odf.catalogSource.name
            value: redhat-operators-snapshot-odf
          - name: odf.catalogSource.image
            value: quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog
          - name: odf.catalogSource.imageTag
            value: v4.12_2023_02_27
          - name: odf.catalogSource.cephStorage.className
            value: gp3-csi
          - name: odf.catalogSource.cephStorage.osdSize
            value: 500Gi
        path: charts/odf
        repoURL: https://github.com/sumiranchugh/agnosticg
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - PruneLast=true